version: '3.0'

services:
  grafana:
    container_name: 'kindling-demo-scenesapp'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-9.5.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/kindling-demo-scenesapp
      - ./provisioning:/etc/grafana/provisioning
