# This is a basic workflow to help you get started with Actions

name: Grafana-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #branches: [release-*]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-grafana:
    if: github.repository == 'KindlingProject/kindling'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set TAG
        run: echo "TAG=latesttest" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}/grafana-plugins
          file: ${{ github.workspace }}/grafana-plugins/Dockerfile
          push: true
          tags: kindlingproject/kindling-grafana:${{env.TAG}}